INSERT INTO PUBLIC.TRANSFER (ID, LENGTH_COST_FACTOR, OPERATOR) VALUES (1, 2.00, 'PKP');
INSERT INTO PUBLIC.TRANSFER (ID, LENGTH_COST_FACTOR, OPERATOR) VALUES (2, 3.00, 'PKP EIC');
INSERT INTO PUBLIC.TRANSFER (ID, LENGTH_COST_FACTOR, OPERATOR) VALUES (3, 3.00, 'ARIVA');
INSERT INTO PUBLIC.TRANSFER (ID, LENGTH_COST_FACTOR, OPERATOR) VALUES (4, 3.00, 'ARIVA');
INSERT INTO PUBLIC.TRANSFER (ID, LENGTH_COST_FACTOR, OPERATOR) VALUES (5, 3.00, 'ARIVA');
