INSERT INTO PUBLIC.STATION (ID, ACRONYM, CITY, NAME) VALUES (1, 'KRK', 'Krakow', 'Krakow Glowny');
INSERT INTO PUBLIC.STATION (ID, ACRONYM, CITY, NAME) VALUES (2, 'WWC', 'Warszawa', 'Warszawa Centralna');
INSERT INTO PUBLIC.STATION (ID, ACRONYM, CITY, NAME) VALUES (3, 'GDS', 'Gdansk', 'Gdansk Glowy');
INSERT INTO PUBLIC.STATION (ID, ACRONYM, CITY, NAME) VALUES (4, 'LDZ', 'Łódź', 'Łódź Fabryczna');
INSERT INTO PUBLIC.STATION (ID, ACRONYM, CITY, NAME) VALUES (5, 'TRN', 'Toruń', 'Toruń Główny');